### ISSUE TITLE
Can not get components/arduino

### ISSUE THREAD

**Issue by n24bass** [m5stack/M5Stack-IDF-old#1]
I could not get a submodule (components/arduino).
It seems to be due to lack of a valid '.gitmodules' file. Is this right?

```
[submodule "components/arduino"]
	path = components/arduino
	url = https://github.com/espressif/arduino-esp32.git
```

**Comment by vibnwis** [comment]
Me too!

**Comment by moononournation** [comment]
I think @m5stack forgot to add all .* files

**Comment by 0x1abin** [comment]
Hi
I used submodule move to the new repositories:
https://github.com/m5stack/M5Stack-IDF
